name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: docker
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: https://github.com/JetBrains/qodana-action@v2025.1
        with:
          args: --linter,,jetbrains/qodana-cdnet:2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}