name: dotnet lib build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x','10.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ZimCom.Core
      - name: Test with dotnet
        run: dotnet test ZimCom.Core --no-restore
      - name: build with dotnet
        run: dotnet build ZimCom.Core --no-restore